spring:
  profiles:
    active: dev

server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://bj-cdb-0ont0bxl.sql.tencentcdb.com:63551/spider?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true
    username: root
    password: hahaha123
    driverClassName: com.mysql.jdbc.Driver
    maximumPoolSize: 10
    validationQuery: select 1
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 3600000
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 10
      max-idle: 5